disabled_rules: # rule identifiers turned on by default to exclude from running
  - trailing_whitespace
  - closure_parameter_position
  - unused_closure_parameter

excluded: # case-sensitive paths to ignore during linting. Takes precedence over `included`
  - WeatherAppTests
  - WeatherAppEndToEndTests
  - WeatherAppCacheIntegrationTests
  - WeatherApp-iOSTests
